### ISSUE TITLE
'KeyboardState' initializer is inaccessible due to 'internal' protection level

### ISSUE THREAD

**Issue by productdevbook** [timdonnelly/KeyboardObserver#1]
<img width="763" alt="Screen Shot 2019-11-03 at 19 55 48" src="https://user-images.githubusercontent.com/38668796/68088837-ef3da700-fe73-11e9-9776-19338073598d.png">

**Comment by timdonnelly** [comment]
Thanks for catching – resolved in 92de4029e60f4c163db08ae00ba79807e4aeb1d5 (and I did a new release).
