### ISSUE TITLE
Argument passed to call that takes no arguments

### ISSUE THREAD

**Issue by productdevbook** [timdonnelly/KeyboardObserver#2]
<img width="782" alt="Screen Shot 2019-11-04 at 09 03 44" src="https://user-images.githubusercontent.com/38668796/68102062-02875b80-fee2-11e9-84f3-db5715bc8985.png">

KeyboardObserver.swift There is an error in the file.

**Comment by timdonnelly** [comment]
Thanks for catching – not sure how Xcode missed that and compiled anyway. Fixed in 95167aa393f2d35d6fb424a20fbebeb29a4b40e1 (and released as 0.1.2)
