### ISSUE TITLE
Keyboard Password

### ISSUE THREAD

**Issue by productdevbook** [timdonnelly/KeyboardObserver#3]
<img width="350" alt="Screen Shot 2019-11-04 at 21 20 04" src="https://user-images.githubusercontent.com/38668796/68146353-dfdc5d80-ff48-11e9-9340-63f366c2c011.png">

keyboard remains under the keyboard when the password is opened. Staying Under

**Comment by timdonnelly** [comment]
It's not clear from the attached image what the problem is. Can you provide a detailed description of what you expect to happen, and what is actually happening?

**Comment by productdevbook** [comment]
![Group](https://user-images.githubusercontent.com/38668796/68148570-50857900-ff4d-11e9-9681-6561252a0cc5.png)
When I click on the password, it does not shift up.

**Comment by timdonnelly** [comment]
Thanks. I can't reproduce on my end, I'm not sure what you're seeing. If you can reproduce in a sample project that you can post I can take a look, but I'm not sure what else is going on in your view hierarchy that might impact this.

**Comment by mkalayci35** [comment]
```
import SwiftUI
import KeyboardObserver
struct SignUp: View {
    
    @State private var state = KeyboardState()
    @Environment(\.presentationMode) var presentationMode: Binding<PresentationMode>
    
    var body: some View {
        GeometryReader { proxy in
        VStack {
            HStack {
                Spacer()
                Text("Don’t have an account?")
                Button(action: {
                    self.presentationMode.wrappedValue.dismiss()
                }) {
                    Text("SIGN UP")
                }.padding(.horizontal)
                    .padding(.vertical, 8)
                    .foregroundColor(Color.white)
                    .background(Color(.black))
                    .cornerRadius(4.0)
            }.padding(EdgeInsets(top: 0, leading: 0, bottom: 70, trailing: 0))
            Spacer()
            HStack {
                
                Text("Text")
                Spacer()
                
            }
            VStack(alignment: .leading) {
                Text("Hello")
                    .fontWeight(.bold)
                    .font(.largeTitle)
                Text("Hello")
                    .fontWeight(.bold)
                    .font(.largeTitle)
                Text("hello")
                    .lineLimit(.none)
            }.padding(EdgeInsets(top: 0, leading: 0, bottom: 45, trailing: 0))
            VStack {
                TextField("Kullanıcı adı", text: /*@START_MENU_TOKEN@*//*@PLACEHOLDER=Value@*/.constant("")/*@END_MENU_TOKEN@*/)
                    .padding(.all)
                    .background(Color(red: 239.0/255.0, green: 243.0/255.0, blue: 244.0/255.0, opacity: 1.0))
                TextField("E-mail", text: /*@START_MENU_TOKEN@*//*@PLACEHOLDER=Value@*/.constant("")/*@END_MENU_TOKEN@*/)
                    .padding(.all)
                    .background(Color(red: 239.0/255.0, green: 243.0/255.0, blue: 244.0/255.0, opacity: 1.0))
                    .cornerRadius(4.0)
                SecureField("Password", text: /*@START_MENU_TOKEN@*//*@PLACEHOLDER=Value@*/.constant("")/*@END_MENU_TOKEN@*/)
                    .padding(.all)
                    .background(Color(red: 239.0/255.0, green: 243.0/255.0, blue: 244.0/255.0, opacity: 1.0))
                    .cornerRadius(4.0)
            }.padding(.bottom, self.state.height(in: proxy))
            Button(action: /*@START_MENU_TOKEN@*/{}/*@END_MENU_TOKEN@*/) {
                HStack {
                    Spacer()
                    Text("Create account")
                    Spacer()
                }
            }.padding(.all)
                .foregroundColor(Color.white)
                .background(Color(.black))
                .cornerRadius(4.0)
        }
            
        }
        .observingKeyboard($state)
    }
}


struct SignUp_Previews: PreviewProvider {
    static var previews: some View {
        SignUp()
    }
}
```

**Comment by productdevbook** [comment]
Image("logo-green") - change your image plase.

```
import SwiftUI
import KeyboardObserver
struct SignUp: View {
    
    @State private var state = KeyboardState()
    @Environment(\.presentationMode) var presentationMode: Binding<PresentationMode>
    
    var body: some View {
        GeometryReader { proxy in
        VStack {
            HStack {
                Spacer()
                Text("Don’t have an account?")
                Button(action: {
                    self.presentationMode.wrappedValue.dismiss()
                }) {
                    Text("SIGN UP")
                }.padding(.horizontal)
                    .padding(.vertical, 8)
                    .foregroundColor(Color.white)
                    .background(Color("jade"))
                    .cornerRadius(4.0)
            }.padding(EdgeInsets(top: 0, leading: 0, bottom: 70, trailing: 0))
            Spacer()
            HStack {
                
                Image("logo-green")
                    .resizable()
                    .aspectRatio(contentMode: ContentMode.fit)
                    .frame(width: 80.0, height: 80.0)
                    .padding(Edge.Set.bottom, 20)
                Spacer()
                
            }
            VStack(alignment: .leading) {
                Text("Hello")
                    .fontWeight(.bold)
                    .font(.largeTitle)
                Text("Hello")
                    .fontWeight(.bold)
                    .font(.largeTitle)
                Text("hello")
                    .lineLimit(.none)
            }.padding(EdgeInsets(top: 0, leading: 0, bottom: 45, trailing: 0))
            VStack {
                TextField("Kullanıcı adı", text: /*@START_MENU_TOKEN@*//*@PLACEHOLDER=Value@*/.constant("")/*@END_MENU_TOKEN@*/)
                    .padding(.all)
                    .background(Color(red: 239.0/255.0, green: 243.0/255.0, blue: 244.0/255.0, opacity: 1.0))
                TextField("E-mail", text: /*@START_MENU_TOKEN@*//*@PLACEHOLDER=Value@*/.constant("")/*@END_MENU_TOKEN@*/)
                    .padding(.all)
                    .background(Color(red: 239.0/255.0, green: 243.0/255.0, blue: 244.0/255.0, opacity: 1.0))
                    .cornerRadius(4.0)
                SecureField("Password", text: /*@START_MENU_TOKEN@*//*@PLACEHOLDER=Value@*/.constant("")/*@END_MENU_TOKEN@*/)
                    .padding(.all)
                    .background(Color(red: 239.0/255.0, green: 243.0/255.0, blue: 244.0/255.0, opacity: 1.0))
                    .cornerRadius(4.0)
            }.padding(.bottom, self.state.height(in: proxy))
            Button(action: /*@START_MENU_TOKEN@*/{}/*@END_MENU_TOKEN@*/) {
                HStack {
                    Spacer()
                    Text("Create account")
                    Spacer()
                }
            }.padding(.all)
                .foregroundColor(Color.white)
                .background(Color(.black))
                .cornerRadius(4.0)
        }
            
        }
        .observingKeyboard($state)
    }
}


struct SignUp_Previews: PreviewProvider {
    static var previews: some View {
        SignUp()
    }
}
```

**Comment by timdonnelly** [comment]
I'm not sure why this code adds keyboard padding in the middle of the hierarchy. This library gives you the height of the keyboard as it overlaps the `GeometryReader`, but this code is inserting padding based on that height somewhere in the middle of the VStack. I would add that padding to the bottom to shift everything up.

In order to follow up with this, I will need a concrete example of: what the library should return for keyboard height, and what is incorrect returned. Closing for now, but please reopen if this turns out to be a library bug.

**Comment by productdevbook** [comment]
<img width="363" alt="Screen Shot 2019-11-04 at 22 45 15" src="https://user-images.githubusercontent.com/38668796/68152466-c6411300-ff54-11e9-993f-7fb17a15e9cf.png">

This is the gray font type keyboard. The keyboard should go up as much as the additional height

**Comment by timdonnelly** [comment]
It's not clear that this is a bug in the library – if you check how tall in points the keyboard is relative to the view that is observing the keyboard, then look at what the library is returning, you can figure out if it is a bug in the library or a bug in your layout code. I unfortunately don't have the time to dig into your specific use of this, but if it can be demonstrated that `keyboardState.height(in:)` is returning the wrong value then I will have something to work with.

Also, have you tried putting your UI in a scroll view? Your UI might simply not fit on screen when the keyboard is up – I don't see anything about your code that would accommodate that situation.

**Comment by productdevbook** [comment]
SecureField("Password", text: $password)
                    .padding(.all)

I understand the problem. Fied does not detect 'padding'. That's why it's halfway. Can you figure this out?

**Comment by timdonnelly** [comment]
This library provides you with the keyboard height, relative to the view that is observing the keyboard: that is all. You can use that keyboard height in your app to update your layout in response to the keyboard.

The library has no knowledge of how your UI is constructed, including your use of `.padding()`. It sounds like this comes down to some confusion about how to use SwiftUI itself, not from a bug in the library. I won't be able to help debug your app-specific code, unfortunately, so I'm leaving this closed.

**Comment by productdevbook** [comment]
I'm sorry, no problem. Everything works regularly.  I made the wrong frame in between. You're a great person. Thank you. sorry for disturbing

**Comment by timdonnelly** [comment]
Oh great, glad you figured it out. It can be tricky to figure out how to think in the SwiftUI layout model at first, but it's really powerful once it clicks. I hope you find this little library useful! I got tired of rewriting this in every project that I worked on.

**Comment by productdevbook** [comment]
Absolutely, the most wonderful library I've ever seen. I shared it in many groups. I'm just doing a code and I'm just looking for a library. You succeeded. Don't forget me in the future because thousands of people will use it. ☺️
