### ISSUE TITLE
GeometryProxy Bug 

### ISSUE THREAD

**Issue by productdevbook** [timdonnelly/KeyboardObserver#4]
<img width="522" alt="Screen Shot 2019-11-04 at 21 33 00" src="https://user-images.githubusercontent.com/38668796/68147224-ae649180-ff4a-11e9-8518-44ad74634967.png">

'GeometryProxy' cannot be constructed because it has no accessible initializers

**Comment by timdonnelly** [comment]
That was a typo in the readme: it should be `GeometryReader` instead of `GeometryProxy`.
