### ISSUE TITLE
macos 10.15 problem

### ISSUE THREAD

**Issue by productdevbook** [timdonnelly/KeyboardObserver#5]
<img width="1174" alt="Screen Shot 2019-11-11 at 21 31 48" src="https://user-images.githubusercontent.com/38668796/68611260-c304d480-04ca-11ea-9a01-6aec663d96a8.png">

**Comment by productdevbook** [comment]
<img width="229" alt="Screen Shot 2019-11-11 at 21 33 12" src="https://user-images.githubusercontent.com/38668796/68611295-dfa10c80-04ca-11ea-8c86-1727cc53b45f.png">

**Comment by timdonnelly** [comment]
This library does not support macOS. As specified in `Package.swift`, it only works on iOS 13+ (as it is the only platform with an onscreen keyboard).
